
version: '3.7'
services:
  psql:
    container_name : gpuai-ubuntu_psql
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: rpFiZszG6pjm6zfW
    volumes:
      - /data/docker/gpuai-ubuntu/db/psql:/var/lib/postgresql/data
    networks:
      - gpuai-ubuntu
  redis:
    container_name : gpuai-ubuntu_redis
    image: redis:6
    restart: unless-stopped
    volumes:
      - /data/docker/gpuai-ubuntu/db/redis:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - gpuai-ubuntu
  cache:
    container_name : gpuai-ubuntu_cache
    image: redis:6
    restart: unless-stopped
    volumes:
      - /tmp/docker/gpuai-ubuntu/cache:/data
      - ./docker/cache.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - gpuai-ubuntu
  pika:
    container_name : gpuai-ubuntu_pika
    image: pikadb/pika
    restart: unless-stopped
    volumes:
      - /tmp/docker/gpuai-ubuntu/pika:/pika/log
      - /data/docker/gpuai-ubuntu/db/pika:/pika/db
    networks:
      - gpuai-ubuntu

  gpuai-ubuntu-zsp:
    container_name : gpuai-ubuntu-zsp
    hostname : gpuai-ubuntu-zsp
    image: gpuai/ubuntu
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    ports:
      - "30100:22"
      - "30108:80"
      - "30110-30113:30010-30013"
    volumes:
      - /data/docker/gpuai-ubuntu/user/zsp/ssh/etc/ssh/host:/etc/ssh/host
      - /data/docker/gpuai-ubuntu/user/zsp/ssh/root/.ssh:/root/.ssh
      - /data/docker/gpuai-ubuntu/user/zsp/_/etc/rc.d:/etc/rc.d
      - /data/docker/gpuai-ubuntu/user/zsp/_/etc/supervisor.d:/etc/supervisor.d
      - /data/docker/gpuai-ubuntu/user/zsp/_/home:/home
      - /data/docker/gpuai-ubuntu/user/zsp/_/root:/root
      - /data/docker/gpuai-ubuntu/share:/share
      - /tmp/docker/gpuai-ubuntu/user/zsp/tmp:/tmp
      - /tmp/docker/gpuai-ubuntu/user/zsp/log:/var/log
      - /var/log/docker/gpuai-ubuntu/zsp/supervisor:/var/log/supervisor
      - /etc/nginx/conf.d/gpuai-ubuntu/zsp:/etc/nginx/conf.d
    networks:
      - gpuai-ubuntu

networks:
  gpuai-ubuntu:

