<%
image=CONFIG.IMAGE
image_id=image.replace("/","-")
docker="/data/docker/%s"%image_id
tmp="/tmp/docker/"+image_id
%>
version: '3.7'
services:
  psql:
    container_name : ${image_id}_psql
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${CONFIG.PSQL.PASSWORD}
    volumes:
      - ${docker}/db/psql:/var/lib/postgresql/data
    networks:
      - ${image_id}
  redis:
    container_name : ${image_id}_redis
    image: redis:6
    restart: unless-stopped
    volumes:
      - ${docker}/db/redis:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - ${image_id}
  cache:
    container_name : ${image_id}_cache
    image: redis:6
    restart: unless-stopped
    volumes:
      - ${tmp}/cache:/data
      - ./docker/cache.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - ${image_id}
  pika:
    container_name : ${image_id}_pika
    image: pikadb/pika
    restart: unless-stopped
    volumes:
      - ${tmp}/pika:/pika/log
      - ${docker}/db/pika:/pika/db
    networks:
      - ${image_id}
% for user,port in CONFIG.USER : 
<%
port = port * 100
docker_user = "%s/user/%s"%(docker, user)
user_disk = "%s/_"%docker_user
%>
  ${image_id}-${user}:
    container_name : ${image_id}-${user}
    hostname : ${image_id}-${user}
    image: ${image}
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    ports:
      - "${30000+port}:22"
      - "${30008+port}:80"
      - "${30010+port}-${30013+port}:30010-30013"
    volumes:
      - ${docker_user}/ssh/etc/ssh/host:/etc/ssh/host
      - ${docker_user}/ssh/root/.ssh:/root/.ssh
      - ${user_disk}/etc/rc.d:/etc/rc.d
      - ${user_disk}/etc/supervisor.d:/etc/supervisor.d
      - ${user_disk}/home:/home
      - ${user_disk}/root:/root
      - ${docker}/share:/share
      - ${tmp}/user/${user}/tmp:/tmp
      - ${tmp}/user/${user}/log:/var/log
      - /var/log/docker/${image_id}/${user}/supervisor:/var/log/supervisor
      - /etc/nginx/conf.d/${image_id}/${user}:/etc/nginx/conf.d
    networks:
      - ${image_id}
    device_requests:
      - capabilities:
        - "gpu"

% endfor 
networks:
  ${image_id}:

